<?php

/**
 * Proxy module for cURL engine.
 *
 * @author Bartosz Firyn (sarxos)
 */


/**
 * Implementation of hook_menu()
 */
function curl_proxy_menu() {

	$items = Array();

	$items['admin/settings/curlproxy'] = Array(
		'title' => 'cURL Proxy',
		'description' => 'Configure proxy settings used by cURL.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('curl_proxy_admin'),
		'file' => 'curl_proxy.admin.inc',
		'access arguments' => Array('administer curlproxy'),
		'type' => MENU_NORMAL_ITEM,
		'weight' => -20,
	);

	return $items;
}

/**
 * Implementation of hook_perm()
 */
function curl_proxy_perm() {
	return Array("administer curlproxy");
}

/**
 * Return proxy settings for cURL or false if proxy is either not used or
 * not set (empty values are permitted).
 *
 * @return Array
 */
function curl_proxy_settings() {

	$host = variable_get("curl_proxy_host", NULL);
	$port = variable_get("curl_proxy_port", NULL);

	$use_proxy = variable_get("curl_proxy_use", false);

	if ($host === NULL || $port === NULL || !$use_proxy) {
		return false;
	}

	return Array(
		"host" => $host,
		"port" => $port,
	);
}
